name: "Linux"

on:
  pull_request:
  push:

jobs:
  stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "loop 'stack test --flag directory-watch:log' --every 5s --unitil-success --num 3"
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --arg cabal true --run "loop 'cabal test -f log' --every 5s --until-success --num 3"
